config/routes.rb
Rails.application.routes.draw do
  resources :routes, except: [:edit, :update, :destroy]

  get 'stats', to: 'routes#stats'

  root 'routes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
  validates_presence_of :starting_point, :end_point
  validate :start_cords_presence, on: :create, if: :starting_point?
  validate :end_cords_presence, on: :create, if: :end_point?

  after_validation :calculate_distance, :set_date

  scope :weekly, lambda {
    where(date: Date.current.beginning_of_week..Date.current.end_of_week).order(:date)
  }

  scope :monthly, lambda {
    where(date: Date.current.beginning_of_month..Date.current.end_of_month).order(:date)
  }

  scope :weekly_stats, -> { weekly.sum(:distance) }

  def start_cords_presence
    !start_cords && errors.add(:starting_point, 'is not correct')
  end

  def end_cords_presence
    !end_cords && errors.add(:end_point, 'is not correct')
  end

  def start_cords
    @start_cords ||= Geocoder.coordinates(starting_point)
  end

  def end_cords
    @end_cords ||= Geocoder.coordinates(end_point)
  end

  def calculate_distance
    self.distance = Geocoder::Calculations.distance_between(start_cords, end_cords)
  end

  def set_date
    self.date = Date.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  def index
    @routes = Route.all
  end

  def show
    @route = Route.find(params[:id])
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to stats_path, notice: 'Created successfully'
    else
      render :new
    end
  end

  def stats
    grouped_routes = Route.monthly.group(:date)

    month_routes_distance_sum = grouped_routes.present? && grouped_routes.sum(:distance).map do |route|
      DailyStatsPresenter.new(route).to_hash
    end

    @routes = month_routes_distance_sum
    @weekly_stats = Route.weekly_stats
  end

  private

  def route_params
    params.require(:route).permit(:starting_point, :end_point)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitofit</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <div class="row text-center">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">FitoFit App</h1>

      <% if message = flash[:notice].presence %>
        <p class="bg-success"><%= message %></p>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/routes/index.html.erb
<h1>Routes</h1>

<table class="table">
  <thead>
  <tr>
    <th>Starting_point</th>
    <th>End_Point</th>
    <th>Distance</th>
    <th>Date</th>
  </tr>
  </thead>
  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.starting_point %></td>
        <td><%= route.end_point %></td>
        <td><%= route.distance %></td>
        <td><%= route.date.strftime("%d.%m.%y") %></td>
        <td><%= link_to 'Show', route_path(route) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Monthly stats by day', stats_path, class: 'button' %>

app/views/routes/new.html.erb
<h3>Add new route</h3>

<%= form_with scope: :route, url: routes_path, local: true do |form| %>
  <% @route.errors.full_messages.each do |msg| %>
    <p class="bg-danger"><%= msg %></p>
  <% end %>
  <p>
    <%= form.label :starting_point %><br>
    <%= form.text_field :starting_point %>
  </p>
  <p>
    <%= form.label :end_point %><br>
    <%= form.text_field :end_point %>
  </p>

  <p>
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </p>
<% end %>

<%= link_to 'Monthly stats by day', stats_path, class: 'btn btn-info' %>

app/views/routes/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-1">
      <table class="table table-striped" style="margin-top: 20px">
        <tr>
        <tr>
          <td class="text-right"><strong>Starting point:</strong></td>
          <td class="text-left"><%= @route.starting_point %></td>
        </tr>
        <tr>
          <td class="text-right"><strong>End point:</strong></td>
          <td class="text-left"><%= @route.end_point %></td>
        </tr>
        <tr>
          <td class="text-right"><strong>Distance:</strong></td>
          <td class="text-left"><%= @route.distance %></td>
        </tr>
        <tr>
          <td class="text-right"><strong>Date:</strong></td>
          <td class="text-left"><%= @route.date.strftime('%d.%m.%y') %></td>
        </tr>
        </tr>
      </table>

      <%= link_to 'Back to all routes', routes_path, class: 'btn btn-default' %>
      <%= link_to 'Add new route', new_route_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/routes/stats.html.erb
<% if @routes %>
  <h3>Stats for <%= @routes.first[:month] %></h3>

  <div class="row text-center">
    <div class="col-md-8 col-md-offset-2">

      <div class="bg-info" style="padding: 20px">This week you have walked <b><%= @weekly_stats %></b> kilometers.</div>

      <h4>Daily stats:</h4>

      <table class="table table-striped">
        <tr>
          <th>Day</th>
          <th>Distance Sum</th>
        </tr>
        <% @routes.each do |route| %>
          <tr class="text-left">
            <td><%= route[:date] %></td>
            <td><%= route[:distance] %></td>
          </tr>
        <% end %>
      </table>
<% else %>

  <div class="bg-info" style="padding: 20px">You have no routes yet.</div>
<% end %>

<%= link_to 'Add new route', new_route_path, class: 'btn btn-primary', style: 'margin-top: 20px' %>
</div>
</div>